n-lina/DailyDash

backend/README.md, backend/package-lock.json, backend/package.json, backend/src/db/database.js, backend/src/firebase/auth.js, backend/src/firebase/firebase.js, backend/src/goals/goals.js, backend/src/goals/goalsHelper.js, backend/src/index.js, backend/src/logger/logging.js, backend/src/notificationServer.js, backend/src/users/users.js
- Fixed most of the backend Codacy issues aside from cossim and getSuggested
- Added a logging library (Winston) to remove console.log outputs
=> Backed Codacy Fixes

.travis.yml, backend/.eslintrc.json, backend/package-lock.json, backend/package.json, backend/src/db/database.js, backend/src/firebase/auth.js, backend/src/goals/goals.js, backend/src/goals/goalsHelper.js, backend/src/index.js, backend/src/notificationServer.js, backend/src/users/users.js
Backend linter should run on travis ci now
Some more backend codacy fixes
=> Added eslint to travis and codacy fixes

backend/.eslintrc.json, backend/src/goals/__mocks__/mockCossim.js, backend/src/goals/__mocks__/mockCossim.test.js, backend/src/goals/cossim.js, backend/src/goals/goals.js, backend/src/goals/goalsSugHelper.js
Of the remaining Codacy backend errors I can remember, /firebase/auth.js has "unnecessary block", but it's a try block, so I think we should just leave it and write about it.
=> fixed most backend codacy issues, and added Jest recognition to ESLint

backend/src/firebase/auth.js, backend/src/index.js
This should fix the last backend codacy issue
=> re-import firebase and fixed try catch

backend/src/goals/goals.js, backend/src/models/goals.js, backend/src/models/users.js, backend/src/users/users.js
- Increments counters for short term goals and user collections
- Requires the userId and shortTermGoal Id
- Returns success field if successful
Will add the specs to the endpoints document
=> Implement Complete Goals Endpoint

frontend/android/app/src/main/java/com/dailydash/MainApplication.java, frontend/app/models/daily-goal/daily-goal.ts, frontend/app/models/goals-store/goals-store.ts, frontend/app/models/user-store/user-store.ts, frontend/app/navigation/home-navigator.tsx, frontend/app/navigation/primary-navigator.tsx, frontend/app/screens/add-goal-screen/add-goal-screen.tsx, frontend/app/screens/awards-screen/awards-screen.tsx, frontend/app/screens/goal-detail-screen/goal-detail-screen.tsx, frontend/app/screens/home-screen/home-screen.tsx, frontend/app/screens/index.ts, frontend/app/screens/ltgoals-screen/ltgoals-screen.tsx, frontend/app/services/api/api.ts, frontend/app/services/api/api.types.ts, frontend/package.json, frontend/yarn.lock
* Setup awards page template with navigation
* Fixed minor styling issues on add goals page
* Setup level to follow the users completed goals
* hooked up completed Goals api with backend
Is the counter endpoint running on the backend right now? I keep getting 404s.
=> Setup goals to sync with database and add awards page

backend/src/users/users.js
User endpoints now need to have authorization header
=> Secure user endpoints

backend/src/goals/goals.js, backend/src/goals/goalsHelper.js, backend/src/users/users.js
Should also persist the timesCompleted counter for each short term goal
Example Request:
PUT http://localhost:3000/goals/5fa50d771f67eb2ed39cf015
```
{
"userId": "testUser3",
"title": "Become",
"description": "irrelevant words",
"shortTermGoals": [
{
"title": "Dofff",
"mon": [
5,
15
],
"wed": [
30,
20
]
},
{
"title": "Every week, make a project",
"sat": [
5,
15
],
"sun": [
30,
20
]
},
{
"title": "Every Sunday, visit a makerspace.",
"mon": [
5,
15
],
"wed": [
30,
20
]
}
]
}
```
=> Implement Update Goals Endpoint

backend/test/performanceTest.py
Based off the script that @jeremywiens wrote for testing user auth security
The average request time is ~0.02 seconds, which is 100x lower than our 2 second goal.
I only tested the MVP state endpoints
=> Add performance test python script

backend/src/goals/goals.js
Currently requires input as query parameter "id"
e.g. POST http://localhost:3000/goals/deleteltg?id=5fa83412bc8b815b7885cbbf
=> added DELETE endpoint for LTGs

backend/src/goals/goalsHelper.js
New PUT request:
```
{
"userId": "testUser3",
"title": "Become",
"description": "irrelevant words",
"shortTermGoals": [
{
"id": "5fadc3d75420422148ff56ea",
"title": "aaddf",
"mon": [
5,
15
],
"wed": [
30,
20
]
}
]
}
```
=> Check id instead of title, persist id when update

backend/src/goals/cossim.js, backend/src/goals/goals.js, backend/src/goals/goalsSugHelper.js
**Inconsistent result issue:** 
Sometimes the same query title results in different suggested STG
**Why I left it as is:**
When the input LTG title has 0 cossim score with all LTG titles it's compared against, it seems that an LTG title is selected as the most similar "at random" (random in the sense that I don't know how it choose, but it chooses one).
The same is true when the input LTG title has 0 cossim score for all STGs it's compared against.
I am content with leaving it as is. We can get consistency by for example checking if all scores are 0, then picking the first alphabetical one, but I don't think that's needed for our functionality? Moreover, it still won't be consistent, since the 50 LTGs being compared changes every couple of minutes (when the cache list of LTGs is against …
=> Implemented mathematical cossim function, and inconsistent result issue resolved (see PR description)

frontend/.detoxrc.json, frontend/app/models/lt-goal-form/lt-goal-form.ts, frontend/app/models/st-goal-form/st-goal-form.ts, frontend/app/screens/add-goal-screen/add-goal-screen.tsx, frontend/app/screens/edit-goal-screen/edit-goal-screen.tsx, frontend/app/screens/goal-detail-screen/goal-detail-screen.tsx, frontend/app/screens/ltgoals-screen/ltgoals-screen.tsx, frontend/e2e/editGoal.e2e.js
implemented form validation for add and edit goals - all fields except description need to be filled in. If users press submit with blank fields, an alert is displayed.  
Right now, I made description optional by making it " " if it is equal to "" (no input). Without this, if users leave the description blank and submit, the goal will not appear on the all goals page. There is no frontend error. Do we need to change something in the backend to make it optional?
=> Form validation

backend/test/authorizationTest.py, frontend/app/models/user-store/user-store.ts
=> Minor doc style fix and default params changed to None

frontend/app/components/button/button.tsx, frontend/app/components/header/header.props.ts, frontend/app/components/header/header.tsx, frontend/app/screens/add-goal-screen/add-goal-screen.tsx, frontend/app/screens/edit-goal-screen/edit-goal-screen.tsx, frontend/app/screens/goal-detail-screen/goal-detail-screen.tsx, frontend/app/screens/home-screen/home-screen.tsx, frontend/app/screens/ltgoals-screen/ltgoals-screen.tsx, frontend/app/screens/profile-screen/profile-screen.tsx, frontend/app/screens/welcome-screen/welcome-screen.tsx
* set global style for buttons in app
* set max width for inputs
* add back button on add new goal screen
I accidentally pushed this to main, but reverted it shortly after.
=> Fixed max width for inputs and set global button style

backend/src/users/users.js
returns goalscompleted when posting to users
=> Add goalscompleted to post users

frontend/app/components/st-time-slot-form/st-time-slot-form.tsx, frontend/app/models/user-store/user-store.ts, frontend/app/screens/awards-screen/awards-screen.tsx, frontend/app/screens/profile-screen/profile-screen.tsx
Just some minor things here and there.
I still can't figure out why the adding goals screen re-renders all the goals sometimes.
Steps to reproduce: 
* Have two stgs
* on the second stg, add another time.
* delete the first stg.
=> Added small fixes here and there

backend/src/goals/__tests__/goals.test.js, backend/test/performanceTest.py
Travis should run successfully
Codacy fixes
=> Fix test and codacy

frontend/app/screens/home-screen/home-screen.tsx, frontend/app/services/api/api.ts
Just change the frontend ui to use an id based on the stgId and the number of times per stg.
=> Bug fix home screen multiple times per stg

backend/src/goals/goalsHelper.js, backend/src/users/users.js
Fixes goals decrementing below zero error
Fixes user initialization DB response error
=> Fix goals decrement

frontend/app/components/st-time-slot-form/st-time-slot-form.tsx, frontend/app/models/time-form/time-form.ts, frontend/app/screens/signin-screen/signin-screen.tsx, frontend/app/screens/welcome-screen/welcome-screen.tsx, frontend/e2e/addGoalAndMarkDone.e2e.js, frontend/e2e/goToAwardsScreen.e2e.js
* fix awards screen test
* fix ui issue on welcome screen
* fix home screen test
* fix big with setting proper time while changing timemode
=> Fix broken detox tests on frontend

frontend/app/models/goals-store/goals-store.ts, frontend/app/screens/goal-form-screen/goal-form-screen.tsx, frontend/app/screens/home-screen/home-screen.tsx
* Fixed some small bugs and random mistakes
* Now a suggestion will only be displayed to the user if it is useful
=> suggestions will not be displayed to user when they are not novel

frontend/app/navigation/goals-navigator.tsx, frontend/app/screens/awards-screen/awards-screen.tsx, frontend/app/screens/common-goals-screen/common-goals-screen.tsx, frontend/app/screens/goal-detail-screen/goal-detail-screen.tsx
* (hack) fixed bug where edit goal button was not available 
* added back button to each screen
=> added back buttons to each nested screen

frontend/app/components/st-time-slot-form/st-time-slot-form.tsx, frontend/e2e/changeTimeMode.e2e.js
* small bug fix to initialize stg form properly
* add timemode test to make sure 12 and 24 hr times are displayed properly
=> Added time mode test

backend/src/goals/__mocks__/mockCossim.test.js, backend/src/goals/__mocks__/mockGoals.test.js, backend/src/goals/__tests__/goals.test.js, backend/src/goals/__tests__/users.test.js, backend/src/goals/cossim.js, backend/src/goals/goals.js, backend/src/goals/goalsHardcoded.js, backend/src/goals/goalsHelper.js
1. Getting full coverage for cossim.js & goals.js using mockCossim.test.js mockGoals.test.js. 
2. Re: integration tests, have mostly covered goal.js, and user.js needs work. Here are remaining uncovered lines:
goals.test.js
goalsHelper.js
Line 18: checks for null array, but can only encounter empty array from the previous operation. However, it never will, given hardcoded goals.
Line 60: Just a curly brace. Not sure why asking for it. Does not "execute". 
Line 97: Not sure why doesn't execute res.end() when rest of code block executes.
Line 101: Don't know how to trigger this
Lines 142 & 147-150: Won't trigger this catch statement unless error in an mongoose operation occurs
Lines 176-183: Not sure how to trigger.
Lines 187 & 189: Unable to trigger (i.e. cannot successfully update a goal) …
=> Integration tests and unmocked cossim
